name: Build & Release Windows EXE

# タグを push したときに実行
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
      # 1. コードをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Python をセットアップ
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # 3. 依存ライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. PyInstaller で exe をビルド
      - name: Build Executable
        run: |
          pyinstaller main.py --onefile --noconsole --clean --version-file=versioninfo.txt --name=PDFMergerTool --icon=pdf-merger-tool.ico --add-data "pdf-merger-tool.ico;."

      # 5. リリースを作成
      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}       # 例: v1.0.0
          release_name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 6. ビルド成果物をリリースにアップロード
      - name: Upload EXE to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/PDFMergerTool.exe
          asset_name: PDFMergerTool.exe
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
